#pragma config(Motor,  port1,           blWheel,       tmotorVex393HighSpeed_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           flWheel,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           trLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           brLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           tlLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           blLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rClaw,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lClaw,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           frWheel,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port10,          brWheel,       tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


//Drive Constants

#define STICK_THRESH 7

//Lift constants

#define LIFT_UP_PWR -127

#define LIFT_DWN_PWR 127

#define LIFT_HOLD_PWR 0


//Claw constants

#define CLAW_HOLD_PWR 15

#define CLAW_OPEN_PWR -127

#define CLAW_CLOSE_PWR 127



//Functions & Macros

#define setDriveL(pwr) motor[flWheel] = \
	motor[blWheel] = \
	pwr
	
#define setDriveR(pwr) motor[frWheel] = \
	motor[brWheel] = \
	pwr

#define setLift(pwr) motor[trLift] = \
	motor[brLift] = \
	motor[tlLift] = \
	motor[blLift] = \
	pwr

#define setClaw(pwr) motor[lClaw] = \
	motor[rClaw] = \
	pwr

	

void setDrive(int lPwr, int rPwr) {
	setDriveL(lPwr);
	setDriveR(rPwr);
}

void setDrive(int pwr) {
	setDriveL(pwr);
	setDriveR(pwr);
}

void setDriveTime(int lPwr, int rPwr, int time) {
	setDrive(lPwr, rPwr);
	wait1Msec(time);
	setDrive(0);
}

void setDriveTime(int pwr, int time) {
	setDrive(pwr);
	wait1Msec(time);
	setDrive(0);
}

void arcade(int move, int rot) {
	setDriveL(move + rot);
	setDriveR(move - rot);
}



/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  setDriveTime(0, 0, 0);
  setDriveTime(0, 0);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol() {
	int liftPwr,
		clawPwr,
		stick[4] = {0, 0, 0, 0};
	while (true) {
	  for(int i = 0; i < 4; i++) {
	  	stick[i] = (fabs(vexRT[i]) > STICK_THRESH)
	  		? vexRT[i]
	  		: 0;
	  }
	  
	  liftPwr = (vexRT[Btn5U] ^ vexRT[Btn5D])
	  	? (vexRT[Btn5U])
	  		? LIFT_UP_PWR
	  		: LIFT_DWN_PWR
	  	: LIFT_HOLD_PWR;
	  	
	  clawPwr = (vexRT[Btn6U] ^ vexRT[Btn6D])
	  	? (vexRT[Btn6U])
	  		? CLAW_CLOSE_PWR
	  		: CLAW_OPEN_PWR
	  	: CLAW_HOLD_PWR;
	  
	  arcade(stick[2], stick[3]);
	  	
	  setLift(liftPwr);
	  
	  setClaw(clawPwr);
	  
	}
}
